"""add_fields_to_event

Revision ID: 2497cd945b7f
Revises: 021ad0aeae1f
Create Date: 2026-03-19 02:02:24.477705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2497cd945b7f'
down_revision: Union[str, Sequence[str], None] = '021ad0aeae1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_venue_event_name', 'events', ['venue_id', 'name'])
    op.add_column('showtimes', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtimes', 'end_time')
    op.drop_constraint('uq_venue_event_name', 'events', type_='unique')
    op.drop_column('events', 'category')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
