"""create ai docs table

Revision ID: 7b9b4842f9f1
Revises: 2b5183dfda2e
Create Date: 2026-04-02 02:55:47.339437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision: str = '7b9b4842f9f1'
down_revision: Union[str, Sequence[str], None] = '2b5183dfda2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_docs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True, comment='Loại nội dung: description, policy, faq, terms, ...'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Thông tin bổ sung: nguồn, độ dài, chunk_index, ...'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Trạng thái kích hoạt'),
    sa.Column('chunk_order', sa.Integer(), nullable=True, comment='Thứ tự chunk nếu nội dung gốc được chia nhỏ'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='Mã ngôn ngữ (vi, en, ...)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_docs_embedding', 'ai_docs', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_ai_docs_event', 'ai_docs', ['event_id'], unique=False)
    op.create_index('idx_ai_docs_type', 'ai_docs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_docs_type', table_name='ai_docs')
    op.drop_index('idx_ai_docs_event', table_name='ai_docs')
    op.drop_index('idx_ai_docs_embedding', table_name='ai_docs', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ai_docs')
    # ### end Alembic commands ###
