"""add status column to ai_docs

Revision ID: ab47f34da577
Revises: a5e2d4c3b1f0
Create Date: 2026-04-02 23:53:11.333004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab47f34da577'
down_revision: Union[str, Sequence[str], None] = 'a5e2d4c3b1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ai_docs_content_tsv', 'ai_docs', [sa.text("to_tsvector('simple', content)")], unique=False, postgresql_using='gin')
    op.create_index('idx_ai_docs_event_active', 'ai_docs', ['event_id', 'is_active'], unique=False)
    op.create_index('idx_ai_docs_metadata', 'ai_docs', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('uniq_event_chunk', 'ai_docs', ['event_id', 'chunk_order'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_event_chunk', table_name='ai_docs')
    op.drop_index('idx_ai_docs_metadata', table_name='ai_docs', postgresql_using='gin')
    op.drop_index('idx_ai_docs_event_active', table_name='ai_docs')
    op.drop_index('idx_ai_docs_content_tsv', table_name='ai_docs', postgresql_using='gin')
    # ### end Alembic commands ###
